dynaconf_merge: True

development:
  weather: <WEATHER_TOKEN>
  telegrambot:
    key: <TELEGRAMBOT_TOKEN>
    admins: [927365427]
    moderated_tread:
    hello_message:
  postgres:
    user: "test"
    password: "qwe123rty456wer"
    port: 5432
    path: "<db_name>"
  redis:
    port: 6969
    path: "/"


development:
  weather: <WEATHER_TOKEN>
  telegrambot:
    key: <TELEGRAMBOT_TOKEN>
    admins: [927365427]
    moderated_tread:
    hello_message:
  postgres:
    user: "test"
    password: "qwe123rty456wer"
    port: 5432
    path: "<db_name>"
  redis:
    port: 6969
    path: "/"